name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with 'v'

jobs:
  test:
    name: Run CI Tests
    uses: ./.github/workflows/ci.yml
    
  build-and-publish:
    name: Build and Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing to PyPI
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1